### ISSUE TITLE
Package dependency issue with gdsfactory

### ISSUE THREAD

**Issue by hpretl** [efabless/ioplace_parser#9]
Hi @donn, another package dependency issue which is causing integration pain on my end:

`omegaconf` used by `gdsfactory` requires `antlr4-python-runtime` 4.9.*, and `ioplace_parser` used by `openlane` wants to see `antlr4-python-runtime` 4.10.0.

Is there any chance you can include 4.9.* in your dependencies for `ioplace_parser`?

**Comment by donn** [comment]
Sure, I can relax the version range. Thanks for catching it before OpenLane 2.1.

**Comment by hpretl** [comment]
Meanwhile, gdsfactory removed omegaconf altogether as a dependency.

**Comment by hpretl** [comment]
Issue sloved, closing it.
